### ISSUE TITLE
UI text Inconsistency when viewing brewing stand and ender chest

### ISSUE THREAD

**Issue by amedott** [Fogg05/CozyUI-Plus#2]
![2024-12-06_22 01 28](https://github.com/user-attachments/assets/2b3c6327-f48a-42a8-b843-872f20326177)
![2024-12-06_22 05 17](https://github.com/user-attachments/assets/f8aee91b-bbed-4d94-bfcf-2308108b120f)

**Comment by Fogg05** [comment]
Thanks for the feedback. In my design, the text of these interface names should be deleted. Reducing unnecessary texts can make the it feels neat and subtle. However, I have not completed the adaptation for foreign languages, which will be fixed in future updates.🥳
